apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app: mc-operator
  template:
    metadata:
      labels:
        app: mc-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}